# Generated by Django 5.1.2 on 2026-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mesa',
            field=models.IntegerField(default=1),
        ),
    ]
