# Generated by Django 5.1.2 on 2026-03-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_venta_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bebida_tipo',
            field=models.CharField(choices=[('soda', 'Soda'), ('jugo_natural', 'Jugo natural'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('plato', 'Plato'), ('bebida', 'Bebida')], default='plato', max_length=10),
        ),
    ]
